theme: minima
title: Welcome
author: Peri
email: arstanbekovaperi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 There will be something here

# social links
github_username:  heteo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
